# Runs the checks for Unified Target configurations
#

variables:
  vmImage: "ubuntu-20.04"

name: $(Build.RequestedFor)_$(Build.SourceBranchName)_$(BuildID)

trigger:
  batch: true
  branches:
    include:
    - master

pr:
  drafts: false
  branches:
    include:
    - master

stages:
- stage: Build
  jobs:
  - job: 'Linux'
    pool:
      vmImage: '$(vmImage)'
    steps:
    - script: make test
      displayName: 'Run the tests'
